CREATE TABLE USER
(
    USER_ID  INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(200),
    USERPASS VARCHAR(200)
);

CREATE TABLE SESSION
(
    SESSION_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER       INTEGER REFERENCES USER (USER_ID),
    START_DATE DATE
)
